package com.tripgo.backend.model.enums;

public enum BusType {

    // SEATER TYPES
    SEATER,
    SEMI_SLEEPER,
    EXECUTIVE_SEATER,
    LUXURY_SEATER,

    // SLEEPER TYPES
    SLEEPER,
    AC_SLEEPER,
    NON_AC_SLEEPER,
    SEMI_SLEEPER_AC,
    SEMI_SLEEPER_NON_AC,

    // MULTI-AXLE
    MULTI_AXLE_SEMI_SLEEPER,
    MULTI_AXLE_SLEEPER,
    MULTI_AXLE_AC_SLEEPER,

    // VOLVO / MERCEDES PREMIUM
    VOLVO_AC,
    VOLVO_MULTI_AXLE,
    VOLVO_SLEEPER,
    VOLVO_MULTI_AXLE_SLEEPER,

    MERCEDES_BENZ_AC,
    MERCEDES_BENZ_SLEEPER,

    // ELECTRIC / SPECIAL
    ELECTRIC,
    MINI_BUS,
    DELUXE,
    SUPER_DELUXE,

    // DEFAULT
    UNKNOWN
}
