export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  OPERATOR_REGISTER: '/operator-register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  OAUTH2_CALLBACK: '/oauth2/callback',
  UNAUTHORIZED: '/unauthorized',
  COMPLETE_PROFILE: '/complete-profile',
  ADMIN_OPERATOR_ACTION: '/admin/operator-action',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_OPERATORS: '/admin/operators',

  DASHBOARD: '/dashboard',
  SEARCH_RESULTS: '/search-results',
  BOOKING: '/booking',
  USER_PROFILE: '/user/profile',
  USER_SETTINGS: '/user/settings',
  USER_SUPPORT: '/user/support',

  OPERATOR_DASHBOARD: '/operator/dashboard',
  OPERATOR_MY_BUSES: '/operator/my-buses',
  OPERATOR_ADD_BUS: '/operator/add-bus',
  OPERATOR_BUS_LAYOUT: '/operator/bus-layout',
  OPERATOR_BUS_REVIEW: '/operator/bus-review',
  OPERATOR_CREATE_ROUTE: '/operator/create-route',
  OPERATOR_SCHEDULES: '/operator/schedules',
  OPERATOR_POLICIES: '/operator/policies',
  OPERATOR_BOOKINGS: '/operator/bookings',
  OPERATOR_DRIVERS: '/operator/drivers',
  OPERATOR_EARNINGS: '/operator/earnings',
  OPERATOR_SETTINGS: '/operator/settings',
  OPERATOR_SUPPORT: '/operator/support',
  PAYMENT: '/payment',
};
