ALTER TABLE route_schedules
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();


ALTER TABLE passengers
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();



ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();


ALTER TABLE payments
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();


ALTER TABLE otp_codes
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();


ALTER TABLE password_resets
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();


ALTER TABLE auth_audit
 ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();
