ALTER TABLE reviews
ADD COLUMN IF NOT EXISTS hidden BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS flagged_reason VARCHAR(500),
ADD COLUMN IF NOT EXISTS moderation_status VARCHAR(50) DEFAULT 'APPROVED';
